# Generated by Django 5.1.4 on 2024-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar catalogo de vehículos')]},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('ford', 'Ford'), ('fiat', 'Fiat'), ('chevrolet', 'Chevrolet'), ('toyota', 'Toyota')], default='ford', max_length=20),
        ),
    ]
