# Generated by Django 5.1.3 on 2024-12-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsmodel',
            options={'permissions': (('es_miembro_1', 'Es miembro con prioridad 1'),)},
        ),
    ]
