# Generated by Django 5.1.3 on 2024-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boardsmodel_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsmodel',
            name='valor',
            field=models.FloatField(),
        ),
    ]
