# Generated by Django 5.1.4 on 2025-01-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(max_length=512),
        ),
    ]
