# Generated by Django 5.1.4 on 2025-01-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0002_alter_proveedor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
