# Generated by Django 5.1.4 on 2025-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0003_alter_proveedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_proveedores/'),
        ),
    ]
