# Generated by Django 5.1.3 on 2024-12-09 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listbook', '0004_alter_inputbookmodel_valoracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputbookmodel',
            options={'permissions': (('development', 'Permiso como desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')), 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='inputbookmodel',
            name='creación',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputbookmodel',
            name='modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
