# Generated by Django 5.1.3 on 2024-12-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listbook', '0005_alter_inputbookmodel_options_inputbookmodel_creación_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAdmin',
            fields=[
                ('inputbookmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listbook.inputbookmodel')),
            ],
            bases=('listbook.inputbookmodel',),
        ),
        migrations.RenameField(
            model_name='inputbookmodel',
            old_name='creación',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='inputbookmodel',
            old_name='modificacion',
            new_name='modificado',
        ),
    ]
