# Generated by Django 5.1.4 on 2024-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0002_tipocombustible_modelocarro_tipo_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocarro',
            name='tipo_combustible',
            field=models.ManyToManyField(blank=True, to='relaciones.tipocombustible'),
        ),
    ]
