# Generated by Django 5.1.4 on 2025-01-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0003_alter_modelocarro_tipo_combustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('automotriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relaciones.automotriz')),
            ],
        ),
    ]
